version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitlife
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  clase:
    build: ./Fullstackfinal/clase
    container_name: clase
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  entrenador:
    build: ./Fullstackfinal/entrenador
    container_name: entrenador
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  evaluacionfisica:
    build: ./Fullstackfinal/evaluacionfisica
    container_name: evaluacionfisica
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  horario:
    build: ./Fullstackfinal/horario
    container_name: horario
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  inventario:
    build: ./Fullstackfinal/inventario
    container_name: inventario
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  membresia:
    build: ./Fullstackfinal/membresia
    container_name: membresia
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notificaciones:
    build: ./Fullstackfinal/notificaciones
    container_name: notificaciones
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  pago:
    build: ./Fullstackfinal/pago
    container_name: pago
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reporte:
    build: ./Fullstackfinal/reporte
    container_name: reporte
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reserva:
    build: ./Fullstackfinal/reserva
    container_name: reserva
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  soporte:
    build: ./Fullstackfinal/soporte
    container_name: soporte
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  usuario:
    build: ./Fullstackfinal/usuario
    container_name: usuario
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mysql_data:
